package basicSeleniumPrograms;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class TestGmail_Login_Page {

	public static void main(String[] args) {
		
		System.setProperty("webdriver.chrome.driver", "E:\\selenium program\\SeleniumWebDriver\\drivers\\chromedriver\\chromedriver.exe");
		
        WebDriver driver = new ChromeDriver();
		
		driver.get("https://www.gmail.com/");
		
		driver.manage().window().maximize();
		
		driver.findElement(By.xpath("//input[@id='identifierId']")).sendKeys("abhiking199520@gmail.com");
		
		driver.findElement(By.xpath("//span[contains(text(),'Next')]")).click();
		
        WebDriverWait wait = new WebDriverWait(driver,60);
		
	    wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//input[@name='password']")));
		
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("#19Hey^11");
		
		driver.findElement(By.xpath("//span[@class='RveJvd snByac' and contains(text(),'Next')]")).click();
		
		wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@class='T-I J-J5-Ji T-I-KE L3']")));
		
		driver.findElement(By.xpath("//div[@class='T-I J-J5-Ji T-I-KE L3']")).click();
		
		System.out.println("Compose button is clicked successfully");
		
		wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//textarea[@id=':ol']")));
		
		driver.findElement(By.xpath("//textarea[@id=':ol']")).sendKeys("mailoabhishek.singh.11@gmail.com");
		
		System.out.println("Recepient email address has entered");
		
		driver.findElement(By.xpath("//input[@name='subjectbox']")).sendKeys("My First Automated email");
		
		String myText = "Hi Abhishek,\nThis email is Auto generated by Software.\nPlease ignore.\nThanks & Regards";
		myText = myText.replace("\n", Keys.chord(Keys.SHIFT, Keys.ENTER));
		driver.findElement(By.xpath("//div[@id=':p8']")).sendKeys(myText);
		
		System.out.println("Message succesfully added for the recepients");
		
		driver.findElement(By.xpath("//div[@id=':nt' and @role='button']")).click();
		
		System.out.println("Message successfully sent");
		
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		
		driver.findElement(By.xpath("//a[@class='gb_b gb_eb gb_R']")).click();
		
		driver.findElement(By.xpath("//a[@id='gb_71']")).click();
		
		Alert alert = driver.switchTo().alert();
        alert.accept();
		
		
		}

}
